name    'saz-php'
version '1.0.4'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage cli, apache and fpm version of php via puppet'
project_page 'https://github.com/saz/puppet-php'
